### ISSUE TITLE
How to update the documentation

### ISSUE THREAD

**Issue by MarcusStrobl** [VForWaTer/documentation#5]
A statement how to update the page on [https://vforwater.github.io/documentation/toolbox/index.html](https://vforwater.github.io/documentation/toolbox/index.html) would be helpful.

**Comment by mmaelicke** [comment]
Hi Marcus,

You need to edit this file: https://github.com/VForWaTer/documentation/blob/master/source/toolbox/index.rst

If you want to reference another file, you can add to the `toctree`. The project is build using sphinx, I guess you know it. If not, their docs are here: https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html

There is also a github action that should in theory build the page and publish it.

**Comment by mmaelicke** [comment]
Hi Marcus,

I saw that all github actions got queued, maybe because the defined action used some deprecated jobs (and a old OS). I updated the `main.yml` and the action directly started and deployed the changes you made. It's all online now!

I'll close the issue as it seems to be solved. If not, please re-open. 
Best,

Mirko
